# Global settings for Netlify
[build]
  command = ""  # Replace with your build command if applicable
  

# Publish settings for HelpMeOut
[[redirects]]
  from = "/HelpMeOut/*"       # Define the URL path for HelpMeOut
  to = "/HelpMeOut/:splat"     # Specify the directory path for HelpMeOut
  status = 200
  publish = "HelpMeOut"       # Specify the directory to publish for HelpMeOut
